Add f17 bt params
nsidc/pm_icecon pull request #39
Opened 2024-01-17 16:43 UTC by sc0tts

This PR adds F17 parameters for both the Bootstrap and the NASATeam algorithms.

2024-01-17 18:04 UTC, trey-stafford requested changes
Needs some cleanup of commented-out code, otherwise looks OK. I think we still need to do some work to streamline how params are handled. Its confusing that we have multiple copies of params in different formats. E.g., 

`NSIDC0001_F17_NORTH_PARAMS`, `BOOTSTRAP_PARAMS_INITIAL_F17_NORTH`, `CDR_F17_NORTH_PARAMS` in `bt/params/nsidc0001.py`.

2024-01-17 18:04 UTC, trey-stafford commented on pm_icecon/bt/params/nsidc0001.py
> +def get_F17_params(
Do we end up using both this and `get_F17_bootstrap_params`?

2024-01-17 18:05 UTC, trey-stafford commented
We should also add an entry to the CHANGELOG!

2024-01-24 19:41 UTC, sc0tts commented on pm_icecon/bt/params/nsidc0001.py
> +# GODDARD_AMSR2_NORTH_PARAMS = ParamsDict(
Yep, that was from dev work.  
The no-longer-useful commented-out lines have been removed.

2024-01-24 20:07 UTC, sc0tts commented on pm_icecon/bt/params/ausi_amsr2.py
> +    # TODO: Need to add a "ame" conditional here
I've split up the AMSRE and the AMSR2 parameter codes.

2024-01-24 20:09 UTC, sc0tts commented on pm_icecon/bt/params/nsidc0001.py
> +# TODO: Is this where we would overwrite the default values?
The TODO is meant to indicate that part of the complexity of this code is that we want to show that the values we use for the CDR are (1) based on the values that are used for the AU_SI12 bootstrap code, but are also (2) overwritten in part by values that we calculated while implementing the algorithm for eCDR.

2024-01-25 18:51 UTC, trey-stafford commented
This PR needs to wait on the release of `pm_tb_data`  v0.3.0.

2024-01-31 23:06 UTC, trey-stafford commented
Declining in favor of https://github.com/nsidc/pm_icecon/pull/45 - better branch name.

2024-01-31 23:06 UTC, closed without merging